"""
LLM provider abstraction used by every agent.

`MockLLMProvider` is the default: a deterministic, rule-based, offline
"reasoning" stand-in. It costs nothing, needs no API key, and has no rate
limit — that is the actual meaning of "unlimited and free" for LLM
reasoning; there is no hosted general-purpose LLM API that is both
unlimited and free, and this project will not pretend otherwise.
`OpenAICompatibleProvider` is a real adapter for when the operator supplies
their own key (any OpenAI-compatible endpoint), used only if
LLM_PROVIDER=openai_compatible is set.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass


@dataclass
class LLMResponse:
    text: str
    provider: str
    model: str


class LLMProvider(ABC):
    @abstractmethod
    def generate(self, system_prompt: str, user_prompt: str) -> LLMResponse: ...


class MockLLMProvider(LLMProvider):
    """Deterministic, template-based reasoning. Not a general-purpose
    language model — this is documented plainly in the README/limitations
    section rather than dressed up as more capable than it is. Each agent
    module supplies its own summarization logic and calls this only to
    produce the final natural-language write-up from structured findings
    it already computed itself, so investigation *quality* does not depend
    on this being a real LLM.
    """

    model_name = "mock-security-analyst-v1"

    def generate(self, system_prompt: str, user_prompt: str) -> LLMResponse:
        # Deliberately simple and inspectable: templated summarization of
        # whatever structured facts the caller put in user_prompt, not
        # free-form generation. This guarantees no hallucinated claims,
        # at the cost of writing that reads more like a report than prose.
        text = (
            "Summary (generated by local mock reasoning provider, not a "
            "general-purpose LLM):\n" + user_prompt.strip()
        )
        return LLMResponse(text=text, provider="mock", model=self.model_name)


class OpenAICompatibleProvider(LLMProvider):
    """Adapter for a real hosted LLM via an OpenAI-compatible /chat/completions
    endpoint. Requires the operator's own api_key and base_url — never
    hard-coded, always from environment variables via core/config.py."""

    def __init__(self, api_key: str, base_url: str, model_name: str):
        if not api_key:
            raise ValueError("OpenAICompatibleProvider requires a non-empty api_key.")
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self.model_name = model_name

    def generate(self, system_prompt: str, user_prompt: str) -> LLMResponse:
        import httpx  # local import: only needed on this real-API path

        payload = {
            "model": self.model_name,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "max_tokens": 800,
            "temperature": 0.2,
        }
        headers = {"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"}
        with httpx.Client(timeout=30.0) as client:
            resp = client.post(f"{self.base_url}/chat/completions", json=payload, headers=headers)
            resp.raise_for_status()
            data = resp.json()
        text = data["choices"][0]["message"]["content"]
        return LLMResponse(text=text, provider="openai_compatible", model=self.model_name)


def get_llm_provider(
    provider: str = "mock",
    api_key: str | None = None,
    base_url: str | None = None,
    model_name: str = "mock-security-analyst-v1",
) -> LLMProvider:
    if provider == "mock":
        return MockLLMProvider()
    if provider == "openai_compatible":
        if not api_key or not base_url:
            raise ValueError("openai_compatible provider requires LLM_API_KEY and LLM_BASE_URL.")
        return OpenAICompatibleProvider(api_key=api_key, base_url=base_url, model_name=model_name)
    raise ValueError(f"Unknown LLM provider: {provider}")
